# Generated by Django 6.0.5 on 2026-05-30 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messages_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('is_from_recipient', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messages_app.compliment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('heart', '❤️ Heart'), ('fire', '🔥 Fire'), ('star', '⭐ Star'), ('hug', '🤗 Hug')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messages_app.compliment')),
                ('reactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('compliment', 'reactor', 'reaction_type')},
            },
        ),
    ]
